// Generated by npm run knowledge. Do not edit by hand.
export const DOCUMENTS: { title: string; text: string; url?: string }[] = [
  {
    "title": "Suraj Jha resume — page 1",
    "text": "SURAJ DEEPAK JHA AI Engineer — Generative AI · LLM Systems · Voice AI 9867751859 | surajjha462002@gmail.com | Mumbai, India (Open to Ahmedabad / Remote) | LinkedIn | GitHub | Portfolio SUMMARY AI Engineer specializing in Generative AI, LLM systems, and real-time Voice AI, with production experience building scalable AI applications for the insurance domain. Experienced in LLM orchestration, RAG, agentic work fl ows, FastAPI, and real-time speech pipelines, including production systems handling 20,000+ calls/day. EXPERIENCE Probus Insurance Broker Private Limited Aug. 2025 – Present AI Engineer Ahmedabad, Gujarat Architected and deployed a production AI voice calling agent handling 20,000+ outbound calls/day for insurance policy renewals, using Pipecat, FastAPI, Twilio, and Sarvam AI with a real-time STT → VAD → LLM → TTS pipeline and",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "using Pipecat, FastAPI, Twilio, and Sarvam AI with a real-time STT → VAD → LLM → TTS pipeline and sub-second turn latency. Built a provider-agnostic LLM orchestration layer spanning multiple providers (OpenAI, Anthropic Claude, Google Gemini, Groq, Mistral, DeepSeek, and others) with automatic health-based failover and live mid-call provider switching, powering intelligent analysis, decision support, and agentic work fl ow automation. Developed vehicle data mapping and normalization pipelines using Python, Pandas, and RapidFuzz with rule-based scoring and insurance-domain validation logic for GCV and PCV quotation work fl ows. Designed MCP server architectures and n8n automation pipelines orchestrating LLMs, REST APIs, and PostgreSQL/Redis databases into scalable production work fl ows. Built RESTful microservices with FastAPI and Flask;",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "databases into scalable production work fl ows. Built RESTful microservices with FastAPI and Flask; automated data extraction from 74+ insurance partner portals using Selenium and async HTTP with rate-limit-safe execution. Operated production AI systems serving thousands of daily user interactions with high availability, using async circuit breakers, Redis-based distributed state, and Prometheus + Grafana observability. KEY PROJECTS & INITIATIVES Voice AI Platform — Architecture & Scale Pipecat | FastAPI | Twilio | Multi-LLM + Multi-STT/TTS Providers Implemented a deterministic state machine resolving ~80% of turns without LLM inference (<50ms latency), plus a per-bot RAG pipeline — OpenAI embeddings, chunked ingestion, cosine-similarity retrieval over PostgreSQL — with S3-backed source storage. Architected production resilience: async",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "retrieval over PostgreSQL — with S3-backed source storage. Architected production resilience: async circuit breakers, AMD gate, TRAI-compliant DNC enforcement, and a custom 500-name phonetics module for Indian name pronunciation across regional languages. Integrated real-time noise cancellation using Silero VAD and DeepFilterNet over Twilio WebSocket audio streams, improving STT accuracy and turn-detection reliability in noisy call environments. Engineered a structured prompt system — call state machine, Hindi objection-handling playbook, anti-hallucination guardrails, and a pronunciation dictionary — to ensure consistent, on-brand agent behavior across languages, re fi ned iteratively from real call recordings. Built the enterprise control plane — a multi-tenant Angular + .NET dashboard with role-based access control, audit trails, live",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "plane — a multi-tenant Angular + .NET dashboard with role-based access control, audit trails, live monitoring, and a function-calling tool framework — deployed via Docker with multi-worker scaling. Intelligent Vehicle Data Mapping System — GCV + PCV Python | RapidFuzz | PostgreSQL | Rule-Based Pipeline Built an end-to-end vehicle master data standardization pipeline processing thousands of records across 15+ insurance partners (HDFC, TATA, ICICI, Bajaj, Digit, SBI, and others) using fuzzy matching, multi- fi eld rule gates (vehicle type, fuel, GVW), and cross- fi eld con fi dence scoring. Directly powers the company's quotation portal — the foundational system enabling premium generation for GCV and PCV insurance lines — with modular per-insurer engines and a PostgreSQL audit trail. Real-Time API Health Intelligence Platform FastAPI |",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "engines and a PostgreSQL audit trail. Real-Time API Health Intelligence Platform FastAPI | asyncio | aiohttp | Streamlit | Prometheus Built a monitoring platform concurrently tracking 74+ insurance partner APIs using Python asyncio + aiohttp, with status classi fi cation (UP/DOWN/SLOW/ERROR), multi-channel alerting (email, Slack, Teams), and smart state-change suppression.",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "Delivered a real-time FastAPI dashboard (SSE) and a Streamlit dashboard (Plotly charts) with per-API isolation, con fi gurable timeouts, and exponential backo ff retries to minimize cascading failures. LLM Applications & MCP Work fl ow Automation OpenAI GPT-4o | Anthropic Claude | Gemini | Ollama | n8n | MCP Built and deployed multiple LLM-powered business applications using OpenAI GPT-4o, Anthropic Claude, Google Gemini, and Ollama (Llama 3) for document analysis, decision support, and automated customer interaction work fl ows. Designed MCP server architectures exposing tools and resources to LLMs for structured reasoning over insurance data; integrated with n8n to orchestrate multi-step agentic pipelines across APIs, databases, and third-party services. Applied prompt engineering techniques (few-shot prompting, structured outputs, tool",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "services. Applied prompt engineering techniques (few-shot prompting, structured outputs, tool calling, prompt evaluation) to improve LLM accuracy on insurance-domain tasks; benchmarked outputs across GPT-4o, Claude, and Gemini for production suitability. TECHNICAL SKILLS Languages: Python, SQL, C++, C#, TypeScript AI / ML: Generative AI, LLMs, RAG, NLP, Machine Learning, Deep Learning, Prompt Engineering, Fine-Tuning (LoRA, QLoRA), Agentic AI, Real-Time Voice AI Voice AI Framework: Pipecat, Twilio Media Streams, Silero/WebRTC VAD STT/TTS Providers: Sarvam AI, Deepgram, ElevenLabs, Cartesia, Azure Speech, Google Speech LLM Providers: OpenAI, Anthropic Claude, Google Gemini, Groq, Mistral, DeepSeek, OpenRouter, Sarvam AI Vector Search / RAG: OpenAI Embeddings (text-embedding-3-small), Cosine-Similarity Retrieval, Semantic Chunking,",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "/ RAG: OpenAI Embeddings (text-embedding-3-small), Cosine-Similarity Retrieval, Semantic Chunking, PostgreSQL- Backed Knowledge Bases Backend & APIs: FastAPI, Flask, REST APIs, WebSockets, AsyncIO, Uvicorn, Gunicorn Engineering: Microservices, Distributed Systems, System Design, Async Programming Agentic & Automation: MCP (Model Context Protocol), Function Calling / Structured Outputs, n8n, Selenium Enterprise / Full-Stack: Angular, .NET, Entity Framework Core, RBAC & Multi-Tenant Architecture Libraries: NumPy, Pandas, Scikit-learn, TensorFlow, RapidFuzz, OpenCV Infra & DevOps: Docker, Docker Compose, Git, Linux, CI/CD, Prometheus, Grafana, Structured Logging (structlog) Cloud: AWS (S3), Azure Databases: PostgreSQL, MySQL, SQLite, Redis Tools: GitHub, Postman, VS Code, Google Colab, PyCharm EDUCATION University of Mumbai — Master of",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "Tools: GitHub, Postman, VS Code, Google Colab, PyCharm EDUCATION University of Mumbai — Master of Computer Applications Sept. 2024 – May 2026 Mumbai, India Nagindas Khandwala College — B.Sc. Computer Science Jun. 2021 – May 2024 Mumbai, India CERTIFICATIONS Cloud Computing and Distributed Systems — NPTEL (Elite), IIT Kanpur — Score: 76% — Jan–Mar 2026 Claude 101 — Anthropic Claude AI Fundamentals — Anthropic",
    "url": "/assets/resume.pdf"
  }
];
