// Generated by npm run knowledge. Do not edit by hand.
export const DOCUMENTS: { title: string; text: string; url?: string }[] = [
  {
    "title": "Suraj Jha resume — page 1",
    "text": "SURAJ DEEPAK JHA \nAI Engineer | Generative AI | LLM Systems | Voice AI \nMumbai, India (Open to Ahmedabad / Remote) | +91 9867751859 | surajjha462002@gmail.com\nLinkedIn: linkedin.com/in/ai-surajjha | GitHub: github.com/Surajj06 | Portfolio: aisurajjha.in \nSUMMARY \n- AI Engineer building Generative AI, LLM, RAG, MCP, and real-time Voice AI systems for insurance\noperations. \n- Experienced in multi-provider LLM orchestration, agentic workflows, retrieval systems, FastAPI, and\nspeech pipelines. \n- Built a configurable voice platform designed for 10,000+ daily calls across concurrent bots, with\nconfigured STT, TTS, and LLM provider adapters. \nEXPERIENCE \nProbus Insurance Broker Private Limited \nAI Engineer | Aug. 2025 - Present | Ahmedabad, Gujarat \n- Architected a configurable AI voice platform for insurance operations, designed for 10,000+",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "\n- Architected a configurable AI voice platform for insurance operations, designed for 10,000+ daily\ncalls across concurrent bots with a real-time STT - VAD - LLM - TTS pipeline. \n- Built provider-agnostic LLM orchestration spanning OpenAI, Anthropic Claude, Google Gemini, Groq,\nMistral, and DeepSeek with health-based failover. \n- Developed vehicle data mapping and normalization pipelines with rule-based scoring and\ninsurance-domain validation for GCV and PCV quotation workflows. \n- Designed MCP server architectures and n8n automation workflows that orchestrate LLMs, REST APIs,\nPostgreSQL, and Redis. \n- Built FastAPI and Flask microservices; automated data extraction from 74+ insurance partner portals\nwith Selenium and async HTTP. \nSELECTED PROJECTS \nAI Voice Calling Platform \n- Pipecat, FastAPI, Twilio, VAD, STT/TTS adapters,",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "\nSELECTED PROJECTS \nAI Voice Calling Platform \n- Pipecat, FastAPI, Twilio, VAD, STT/TTS adapters, multi-provider LLM failover, RAG, PostgreSQL, Redis,\nAngular, .NET, Docker, Prometheus, Grafana. \nVehicle Catalogue Matching Engine \n- Python, pandas, RapidFuzz, PostgreSQL, and audit trails for GCV/PCV partner catalogue normalization. \nAPI Health Monitor \n- Async FastAPI monitor for 74+ partner APIs with UP/SLOW/DOWN/ERROR classification and Email, Slack,\nTeams alerts.",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "SURAJ DEEPAK JHA \nAI ENGINEER - PROJECTS, SKILLS, AND EDUCATION \nMORE PROJECT WORK \nStock Intelligence Engine \n- FastAPI stock-research system combining price technicals, 11 news feeds, FinBERT, sentence-transformers,\nFAISS, and an OpenAI or local Ollama analysis option. \nWhatsApp Document Verification Bot \n- FastAPI, WhatsApp Cloud API, OpenCV/Tesseract, PostgreSQL, sentence-transformers, FAISS, and Fernet\nencryption for privacy-first document processing. \nConversational Quote Assistant \n- Flask chat flow that collects insurance details and calls insurer quotation APIs, with transparent demo\nfallbacks when a provider is unavailable. \nTECHNICAL SKILLS \nAI and agentic systems \n- Generative AI, LLM systems, RAG, Agentic AI, MCP, function calling, structured outputs, prompt\nengineering, NLP, machine learning. \nLLM providers and local AI \n-",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "structured outputs, prompt\nengineering, NLP, machine learning. \nLLM providers and local AI \n- OpenAI, Anthropic Claude, Google Gemini, Groq, Mistral, DeepSeek, Ollama. \nVoice AI \n- Pipecat, Twilio Media Streams, Silero/WebRTC VAD, Sarvam AI, Deepgram, ElevenLabs, Cartesia, Azure\nSpeech. \nBackend and data \n- Python, FastAPI, Flask, REST APIs, WebSockets, Server-Sent Events, AsyncIO, C#, .NET, ASP.NET Core,\nPostgreSQL, MySQL, Redis, SQLite. \nRetrieval, data, and delivery \n- sentence-transformers, FAISS, FinBERT, Pandas, RapidFuzz, NumPy, scikit-learn, Docker, Git, Linux,\nCI/CD, Prometheus, Grafana, AWS S3, Azure. \nEDUCATION AND CERTIFICATIONS \nUniversity of Mumbai - Master of Computer Applications \nSept. 2024 - May 2026 | Mumbai, India \nNagindas Khandwala College - B.Sc. Computer Science \nJun. 2021 - May 2024 | Mumbai, India \nCertification:",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "Khandwala College - B.Sc. Computer Science \nJun. 2021 - May 2024 | Mumbai, India \nCertification: Cloud Computing and Distributed Systems - NPTEL (Elite), IIT Kanpur - Score: 76% - Jan-Mar 2026\nClaude 101 - Anthropic Claude AI Fundamentals - Anthropic\nReferences and detailed case studies are available through the portfolio.",
    "url": "/assets/resume.pdf"
  }
];
