// Generated by npm run knowledge. Do not edit by hand.
export const DOCUMENTS: { title: string; text: string; url?: string }[] = [
  {
    "title": "Suraj Jha resume — page 1",
    "text": "SURAJ DEEPAK JHA \nAI Engineer — Generative AI · LLM Systems · Voice AI \n9867751859 | surajjha462002@gmail.com | Mumbai, India (Open to Ahmedabad / Remote) | LinkedIn | GitHub | Portfolio \nSUMMARY \nAI Engineer specializing in Generative AI, LLM systems, and real-time Voice AI, with production experience building scalable AI\napplications for the insurance domain. Experienced in LLM orchestration, RAG, agentic work fl ows, FastAPI, and real-time speech\npipelines, including production systems handling 20,000+ calls/day. \nEXPERIENCE \nProbus Insurance Broker Private Limited Aug. 2025 – Present \nAI Engineer Ahmedabad, Gujarat \nArchitected and deployed a production AI voice calling agent handling 20,000+ outbound calls/day for insurance policy\nrenewals, using Pipecat, FastAPI, Twilio, and Sarvam AI with a real-time STT → VAD → LLM → TTS pipeline",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "using Pipecat, FastAPI, Twilio, and Sarvam AI with a real-time STT → VAD → LLM → TTS pipeline and sub-second turn\nlatency. \nBuilt a provider-agnostic LLM orchestration layer spanning multiple providers (OpenAI, Anthropic Claude, Google Gemini, Groq,\nMistral, DeepSeek, and others) with automatic health-based failover and live mid-call provider switching, powering intelligent\nanalysis, decision support, and agentic work fl ow automation. \nDeveloped vehicle data mapping and normalization pipelines using Python, Pandas, and RapidFuzz with rule-based scoring and\ninsurance-domain validation logic for GCV and PCV quotation work fl ows. \nDesigned MCP server architectures and n8n automation pipelines orchestrating LLMs, REST APIs, and PostgreSQL/Redis\ndatabases into scalable production work fl ows. \nBuilt RESTful microservices with FastAPI and",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "into scalable production work fl ows. \nBuilt RESTful microservices with FastAPI and Flask; automated data extraction from 74+ insurance partner portals using\nSelenium and async HTTP with rate-limit-safe execution. \nOperated production AI systems serving thousands of daily user interactions with high availability, using async circuit breakers,\nRedis-based distributed state, and Prometheus + Grafana observability. \nKEY PROJECTS & INITIATIVES \nVoice AI Platform — Architecture & Scale \nPipecat | FastAPI | Twilio | Multi-LLM + Multi-STT/TTS Providers \nImplemented a deterministic state machine resolving ~80% of turns without LLM inference (<50ms latency), plus a per-bot RAG\npipeline — OpenAI embeddings, chunked ingestion, cosine-similarity retrieval over PostgreSQL — with S3-backed source\nstorage.\nArchitected production resilience: async",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "retrieval over PostgreSQL — with S3-backed source\nstorage.\nArchitected production resilience: async circuit breakers, AMD gate, TRAI-compliant DNC enforcement, and a custom 500-name\nphonetics module for Indian name pronunciation across regional languages.\nIntegrated real-time noise cancellation using Silero VAD and DeepFilterNet over Twilio WebSocket audio streams, improving STT\naccuracy and turn-detection reliability in noisy call environments.\nEngineered a structured prompt system — call state machine, Hindi objection-handling playbook, anti-hallucination guardrails,\nand a pronunciation dictionary — to ensure consistent, on-brand agent behavior across languages, re fi ned iteratively from real\ncall recordings.\nBuilt the enterprise control plane — a multi-tenant Angular + .NET dashboard with role-based access control, audit trails,",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "plane — a multi-tenant Angular + .NET dashboard with role-based access control, audit trails, live\nmonitoring, and a function-calling tool framework — deployed via Docker with multi-worker scaling. \nIntelligent Vehicle Data Mapping System — GCV + PCV \nPython | RapidFuzz | PostgreSQL | Rule-Based Pipeline \nBuilt an end-to-end vehicle master data standardization pipeline processing thousands of records across 15+ insurance partners\n(HDFC, TATA, ICICI, Bajaj, Digit, SBI, and others) using fuzzy matching, multi- fi eld rule gates (vehicle type, fuel, GVW), and cross- \nfi eld con fi dence scoring.\nDirectly powers the company's quotation portal — the foundational system enabling premium generation for GCV and PCV\ninsurance lines — with modular per-insurer engines and a PostgreSQL audit trail. \nReal-Time API Health Intelligence Platform \nFastAPI",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 1",
    "text": "engines and a PostgreSQL audit trail. \nReal-Time API Health Intelligence Platform \nFastAPI | asyncio | aiohttp | Streamlit | Prometheus \nBuilt a monitoring platform concurrently tracking 74+ insurance partner APIs using Python asyncio + aiohttp, with status\nclassi fi cation (UP/DOWN/SLOW/ERROR), multi-channel alerting (email, Slack, Teams), and smart state-change suppression.",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "Delivered a real-time FastAPI dashboard (SSE) and a Streamlit dashboard (Plotly charts) with per-API isolation, con fi gurable\ntimeouts, and exponential backo ff retries to minimize cascading failures. \nLLM Applications & MCP Work fl ow Automation \nOpenAI GPT-4o | Anthropic Claude | Gemini | Ollama | n8n | MCP \nBuilt and deployed multiple LLM-powered business applications using OpenAI GPT-4o, Anthropic Claude, Google Gemini, and\nOllama (Llama 3) for document analysis, decision support, and automated customer interaction work fl ows.\nDesigned MCP server architectures exposing tools and resources to LLMs for structured reasoning over insurance data;\nintegrated with n8n to orchestrate multi-step agentic pipelines across APIs, databases, and third-party services.\nApplied prompt engineering techniques (few-shot prompting, structured outputs,",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "services.\nApplied prompt engineering techniques (few-shot prompting, structured outputs, tool calling, prompt evaluation) to improve\nLLM accuracy on insurance-domain tasks; benchmarked outputs across GPT-4o, Claude, and Gemini for production suitability. \nTECHNICAL SKILLS \nLanguages: Python, SQL, C++, C#, TypeScript \nAI / ML: Generative AI, LLMs, RAG, NLP, Machine Learning, Deep Learning, Prompt Engineering, Fine-Tuning (LoRA, QLoRA), Agentic\nAI, Real-Time Voice AI \nVoice AI Framework: Pipecat, Twilio Media Streams, Silero/WebRTC VAD \nSTT/TTS Providers: Sarvam AI, Deepgram, ElevenLabs, Cartesia, Azure Speech, Google Speech \nLLM Providers: OpenAI, Anthropic Claude, Google Gemini, Groq, Mistral, DeepSeek, OpenRouter, Sarvam AI \nVector Search / RAG: OpenAI Embeddings (text-embedding-3-small), Cosine-Similarity Retrieval, Semantic Chunking,",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "/ RAG: OpenAI Embeddings (text-embedding-3-small), Cosine-Similarity Retrieval, Semantic Chunking, PostgreSQL-\nBacked Knowledge Bases \nBackend & APIs: FastAPI, Flask, REST APIs, WebSockets, AsyncIO, Uvicorn, Gunicorn \nEngineering: Microservices, Distributed Systems, System Design, Async Programming \nAgentic & Automation: MCP (Model Context Protocol), Function Calling / Structured Outputs, n8n, Selenium \nEnterprise / Full-Stack: Angular, .NET, Entity Framework Core, RBAC & Multi-Tenant Architecture \nLibraries: NumPy, Pandas, Scikit-learn, TensorFlow, RapidFuzz, OpenCV \nInfra & DevOps: Docker, Docker Compose, Git, Linux, CI/CD, Prometheus, Grafana, Structured Logging (structlog) \nCloud: AWS (S3), Azure \nDatabases: PostgreSQL, MySQL, SQLite, Redis \nTools: GitHub, Postman, VS Code, Google Colab, PyCharm \nEDUCATION \nUniversity of Mumbai —",
    "url": "/assets/resume.pdf"
  },
  {
    "title": "Suraj Jha resume — page 2",
    "text": "Redis \nTools: GitHub, Postman, VS Code, Google Colab, PyCharm \nEDUCATION \nUniversity of Mumbai — Master of Computer Applications Sept. 2024 – May 2026 \nMumbai, India \nNagindas Khandwala College — B.Sc. Computer Science Jun. 2021 – May 2024 \nMumbai, India \nCERTIFICATIONS \nCloud Computing and Distributed Systems — NPTEL (Elite), IIT Kanpur — Score: 76% — Jan–Mar 2026 \nClaude 101 — Anthropic Claude AI Fundamentals — Anthropic",
    "url": "/assets/resume.pdf"
  }
];
